// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pbgo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExampleClient is the client API for Example service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExampleClient interface {
	Unary(ctx context.Context, in *Unary_Request, opts ...grpc.CallOption) (*Unary_Response, error)
	StreamResponse(ctx context.Context, in *Stream_Request, opts ...grpc.CallOption) (Example_StreamResponseClient, error)
	StreamRequest(ctx context.Context, opts ...grpc.CallOption) (Example_StreamRequestClient, error)
	StreamDuplex(ctx context.Context, opts ...grpc.CallOption) (Example_StreamDuplexClient, error)
}

type exampleClient struct {
	cc grpc.ClientConnInterface
}

func NewExampleClient(cc grpc.ClientConnInterface) ExampleClient {
	return &exampleClient{cc}
}

func (c *exampleClient) Unary(ctx context.Context, in *Unary_Request, opts ...grpc.CallOption) (*Unary_Response, error) {
	out := new(Unary_Response)
	err := c.cc.Invoke(ctx, "/errors.Example/Unary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) StreamResponse(ctx context.Context, in *Stream_Request, opts ...grpc.CallOption) (Example_StreamResponseClient, error) {
	stream, err := c.cc.NewStream(ctx, &Example_ServiceDesc.Streams[0], "/errors.Example/StreamResponse", opts...)
	if err != nil {
		return nil, err
	}
	x := &exampleStreamResponseClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Example_StreamResponseClient interface {
	Recv() (*Stream_Response, error)
	grpc.ClientStream
}

type exampleStreamResponseClient struct {
	grpc.ClientStream
}

func (x *exampleStreamResponseClient) Recv() (*Stream_Response, error) {
	m := new(Stream_Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *exampleClient) StreamRequest(ctx context.Context, opts ...grpc.CallOption) (Example_StreamRequestClient, error) {
	stream, err := c.cc.NewStream(ctx, &Example_ServiceDesc.Streams[1], "/errors.Example/StreamRequest", opts...)
	if err != nil {
		return nil, err
	}
	x := &exampleStreamRequestClient{stream}
	return x, nil
}

type Example_StreamRequestClient interface {
	Send(*Stream_Request) error
	CloseAndRecv() (*Stream_Response, error)
	grpc.ClientStream
}

type exampleStreamRequestClient struct {
	grpc.ClientStream
}

func (x *exampleStreamRequestClient) Send(m *Stream_Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *exampleStreamRequestClient) CloseAndRecv() (*Stream_Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Stream_Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *exampleClient) StreamDuplex(ctx context.Context, opts ...grpc.CallOption) (Example_StreamDuplexClient, error) {
	stream, err := c.cc.NewStream(ctx, &Example_ServiceDesc.Streams[2], "/errors.Example/StreamDuplex", opts...)
	if err != nil {
		return nil, err
	}
	x := &exampleStreamDuplexClient{stream}
	return x, nil
}

type Example_StreamDuplexClient interface {
	Send(*Stream_Request) error
	Recv() (*Stream_Response, error)
	grpc.ClientStream
}

type exampleStreamDuplexClient struct {
	grpc.ClientStream
}

func (x *exampleStreamDuplexClient) Send(m *Stream_Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *exampleStreamDuplexClient) Recv() (*Stream_Response, error) {
	m := new(Stream_Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExampleServer is the server API for Example service.
// All implementations must embed UnimplementedExampleServer
// for forward compatibility
type ExampleServer interface {
	Unary(context.Context, *Unary_Request) (*Unary_Response, error)
	StreamResponse(*Stream_Request, Example_StreamResponseServer) error
	StreamRequest(Example_StreamRequestServer) error
	StreamDuplex(Example_StreamDuplexServer) error
	mustEmbedUnimplementedExampleServer()
}

// UnimplementedExampleServer must be embedded to have forward compatible implementations.
type UnimplementedExampleServer struct {
}

func (UnimplementedExampleServer) Unary(context.Context, *Unary_Request) (*Unary_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unary not implemented")
}
func (UnimplementedExampleServer) StreamResponse(*Stream_Request, Example_StreamResponseServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamResponse not implemented")
}
func (UnimplementedExampleServer) StreamRequest(Example_StreamRequestServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamRequest not implemented")
}
func (UnimplementedExampleServer) StreamDuplex(Example_StreamDuplexServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamDuplex not implemented")
}
func (UnimplementedExampleServer) mustEmbedUnimplementedExampleServer() {}

// UnsafeExampleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExampleServer will
// result in compilation errors.
type UnsafeExampleServer interface {
	mustEmbedUnimplementedExampleServer()
}

func RegisterExampleServer(s grpc.ServiceRegistrar, srv ExampleServer) {
	s.RegisterService(&Example_ServiceDesc, srv)
}

func _Example_Unary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Unary_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServer).Unary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/errors.Example/Unary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServer).Unary(ctx, req.(*Unary_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Example_StreamResponse_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Stream_Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExampleServer).StreamResponse(m, &exampleStreamResponseServer{stream})
}

type Example_StreamResponseServer interface {
	Send(*Stream_Response) error
	grpc.ServerStream
}

type exampleStreamResponseServer struct {
	grpc.ServerStream
}

func (x *exampleStreamResponseServer) Send(m *Stream_Response) error {
	return x.ServerStream.SendMsg(m)
}

func _Example_StreamRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExampleServer).StreamRequest(&exampleStreamRequestServer{stream})
}

type Example_StreamRequestServer interface {
	SendAndClose(*Stream_Response) error
	Recv() (*Stream_Request, error)
	grpc.ServerStream
}

type exampleStreamRequestServer struct {
	grpc.ServerStream
}

func (x *exampleStreamRequestServer) SendAndClose(m *Stream_Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *exampleStreamRequestServer) Recv() (*Stream_Request, error) {
	m := new(Stream_Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Example_StreamDuplex_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExampleServer).StreamDuplex(&exampleStreamDuplexServer{stream})
}

type Example_StreamDuplexServer interface {
	Send(*Stream_Response) error
	Recv() (*Stream_Request, error)
	grpc.ServerStream
}

type exampleStreamDuplexServer struct {
	grpc.ServerStream
}

func (x *exampleStreamDuplexServer) Send(m *Stream_Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *exampleStreamDuplexServer) Recv() (*Stream_Request, error) {
	m := new(Stream_Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Example_ServiceDesc is the grpc.ServiceDesc for Example service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Example_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "errors.Example",
	HandlerType: (*ExampleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unary",
			Handler:    _Example_Unary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamResponse",
			Handler:       _Example_StreamResponse_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamRequest",
			Handler:       _Example_StreamRequest_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamDuplex",
			Handler:       _Example_StreamDuplex_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "server.proto",
}
