// Code generated by protoc-gen-pw-errors. DO NOT EDIT.
package pbgo

import (
	fmt "fmt"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

func (x *NotAuthenticated) GRPCStatus() *status.Status {
	return status.New(codes.Code(10), x.Error())
}

func (x *NotAuthenticated) HTTPStatus() int {
	return 401
}

func (x *NotAuthenticated) Error() string {
	return fmt.Sprintf("NotAuthenticatedError: ")
}

func (x *NotAuthorized) GRPCStatus() *status.Status {
	return status.New(codes.Code(11), x.Error())
}

func (x *NotAuthorized) HTTPStatus() int {
	return 403
}

func (x *NotAuthorized) Error() string {
	return fmt.Sprintf("'%s' is not allowed to access resource '%s'", x.Subject, x.Resource)
}

func (x *NotFound) GRPCStatus() *status.Status {
	return status.New(codes.Code(20), x.Error())
}

func (x *NotFound) HTTPStatus() int {
	return 404
}

func (x *NotFound) Temporary() {}

func (x *NotFound) Error() string {
	return fmt.Sprintf("NotFoundError: resource = %s", x.Resource)
}
