// Code generated by protoc-gen-pw-validator. DO NOT EDIT.
package openapi_pb

import (
	validator "github.com/joesonw/proto-web/pkg/validator"
)

func (x *Tag) Validate() error {
	if err := validator.Var(x.Name, "required"); err != nil {
		return err
	}
	if err := x.ExternalDocs.Validate(); err != nil {
		return err
	}
	return nil
}
func (x *Info) Validate() error {
	if err := validator.Var(x.Title, "required"); err != nil {
		return err
	}
	if err := x.Contact.Validate(); err != nil {
		return err
	}
	if err := x.License.Validate(); err != nil {
		return err
	}
	if err := validator.Var(x.Version, "required"); err != nil {
		return err
	}
	return nil
}
func (x *Contact) Validate() error {
	return nil
}
func (x *License) Validate() error {
	if err := validator.Var(x.Name, "required"); err != nil {
		return err
	}
	return nil
}
func (x *Server) Validate() error {
	return nil
}
func (x *ServerVariable) Validate() error {
	if err := validator.Var(x.Default, "required"); err != nil {
		return err
	}
	return nil
}
func (x *ExternalDocumentation) Validate() error {
	return nil
}
func (x *SecurityRequirement) Validate() error {
	return nil
}
